import type { LiquidFilter } from "./filter.types";

export const stringFilters: LiquidFilter[] = [
  {
    label: "append",
    detail: "string | append: string",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Adds a given string to the end of a string.",
  },
  {
    label: "capitalize",
    detail: "string | capitalize",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Capitalizes the first word in a string and downcases the remaining characters.",
  },
  {
    label: "downcase",
    detail: "string | downcase",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Converts a string to all lowercase characters.",
  },
  {
    label: "escape",
    detail: "string | escape",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation:
      "Escapes special characters in HTML, such as <>, ', and &, and converts characters into escape sequences. The filter doesn't effect characters within the string that don’t have a corresponding escape sequence.",
  },
  {
    label: "escape_once",
    detail: "string | escape_once",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Escapes a string without changing characters that have already been escaped.",
  },
  {
    label: "lstrip",
    detail: "string | lstrip",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Strips all whitespace from the left of a string.",
  },
  {
    label: "newline_to_br",
    detail: "string | newline_to_br",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Converts newlines (\n) in a string to HTML line breaks (<br>).",
  },
  {
    label: "prepend",
    detail: "string | prepend: string",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Adds a given string to the beginning of a string.",
    insertText: "prepend: ${1}",
  },
  {
    label: "remove",
    detail: "string | remove: string",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Removes any instance of a substring inside a string.",
    insertText: 'remove: "${1}"',
  },
  {
    label: "remove_first",
    detail: "string | remove_first: string",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Removes the first instance of a substring inside a string.",
    insertText: 'remove_first: "${1}"',
  },
  {
    label: "remove_last",
    detail: "string | remove_last: string",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Removes the last instance of a substring inside a string.",
    insertText: 'remove_last: "${1}"',
  },
  {
    label: "replace",
    detail: "string | replace: string, string",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Replaces any instance of a substring inside a string with a given string.",
    insertText: 'replace: "${1}", "${2}"',
  },
  {
    label: "replace_first",
    detail: "string | replace_first: string, string",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Replaces the first instance of a substring inside a string with a given string.",
    insertText: 'replace_first: "${1}", "${2}"',
  },
  {
    label: "replace_last",
    detail: "string | replace_last: string, string",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Replaces the last instance of a substring inside a string with a given string.",
    insertText: 'replace_last: "${1}", "${2}"',
  },
  {
    label: "rstrip",
    detail: "string | rstrip",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Strips all whitespace from the right of a string.",
    insertText: 'rstrip: "${1}", "${2}"',
  },
  {
    label: "slice",
    detail: "string | slice: number, number",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Returns a substring or series of array items, starting at a given 0-based index.",
  },
  {
    label: "split",
    detail: "string | split: string",
    acceptedTypes: ["string"],
    returnType: "array",
    documentation: "Splits a string into an array of substrings based on a given separator.",
    insertText: 'split: "${1}"',
  },
  {
    label: "strip",
    detail: "string | split",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Strips all whitespace from the left and right of a string.",
  },
  {
    label: "strip_html",
    detail: "string | strip_html",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Strips all HTML tags from a string.",
  },
  {
    label: "strip_newlines",
    detail: "string | strip_newlines",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Strips all newline characters (line breaks) from a string.",
  },
  {
    label: "truncate",
    detail: "string | truncate: number, string",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation:
      "Truncates a string down to a given number of characters. If the specified number of characters is less than the length of the string, then an ellipsis (...) is appended to the truncated string. The ellipsis is included in the character count of the truncated string.",
    insertText: "truncate: ${1}",
  },
  {
    label: "truncatewords",
    detail: "string | truncatewords: number, string",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation:
      "Truncates a string down to a given number of words. If the specified number of words is less than the number of words in the string, then an ellipsis (...) is appended to the truncated string.",
    insertText: "truncatewords: ${1}",
  },
  {
    label: "upcase",
    detail: "string | upcase",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Converts a string to all uppercase characters.",
  },
  {
    label: "url_decode",
    detail: "string | url_decode",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Decodes any percent-encoded characters in a string.",
  },
  {
    label: "url_encode",
    detail: "string | url_encode",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Converts any URL-unsafe characters in a string to the percent-encoded equivalent.",
  },
  {
    label: "uri_escape",
    detail: "string | uri_escape",
    acceptedTypes: ["string"],
    returnType: "string",
    documentation: "Escapes any URL-unsafe characters in a string.",
  },
];
